version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.13.1
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@8.1.3
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --prod
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/javatechie-covid19-tracker/ s3://tapankumarachary --delete